### PR TITLE
Spring Boot 3

### PR DESCRIPTION
**Pull request by sp00m**

### CODE REVIEW

**Comment by sp00m** [comment]
https://github.com/wiremock/wiremock/pull/1942

**Comment by AntonOellerer** [comment]
Hey, now that wiremock merged it jetty 11 support, do you have an estimation when you can merge this PR?
Thank you for your work!

**Comment by mohsen0** [comment]
> Hey, now that wiremock merged it jetty 11 support, do you have an estimation when you can merge this PR? Thank you for your work!

PRs are welcomed, otherwise, it might take some time.

**Review by mohsen0 — DISMISSED** [review]

**Comment by mohsen0** [comment]
Moved in here https://github.com/qudini/qudini-reactive/pull/210

**Pull request closed without merging**
